### ISSUE TITLE
NB 01: Section 12 visualizing CNN code fix

### ISSUE THREAD

**Issue by magitz** [PracticumAI/computer_vision#19]
Something is off in the code for visualizing the CNN. Or maybe I am misunderstanding the image. But the right hand original image can't result in the right hand output...they are different images

![image](https://github.com/user-attachments/assets/fd6da3d1-0915-4d91-af2e-493ee4c56135)

**Comment by ilutticken** [comment]
If I'm understanding your comment correctly, you're asking why "Original Image 2" and "Feature Map 1, Channel 2" don't match? That is my error. All three feature map images are from "Original Image 1" with each of the 3 shown filters run over it. I pulled three original images instead of one for visual symmetry...

I can get rid of the first and last Original Images if you think it's confusing.

**Comment by magitz** [comment]
Yes. I would either just have the Original image 1 in the middle of that row or replicate it 3 times. Either way, call it "Original image" (without the 1). I hadn't noticed that the left image is also different.

I go back and forth on whether I think the filters should be represented as images as you have here or just the 3x3 matrices of numbers. Part of me thinks the matrix would be more consistent with the way we cover the kernel.

**Comment by magitz** [comment]
Merged. Closing
